# Nachbildung Mathematischer Operationen durch ML-Modelle

## 1. Erstellung der Datensätze

## 1.1 Trainingsdaten

In [1]:
# import numpy as np
# import pandas as pd

# N = 100000

# x1 = np.random.uniform(-10, 10, N)
# x2 = np.random.uniform(-10, 10, N)

# y = x1 + x2   # oder x1 * x2, x1 - x2

# data = pd.DataFrame({
#     "x1": x1,
#     "x2": x2,
#     "y": y
# })

# data.to_csv("addition_dataset.csv", index=False)

## 1.2 Generalisierungsdatensätze

In [2]:
# import numpy as np
# import pandas as pd

# N_gen = 100_000

# # Neuer Wertebereich (nicht im Training enthalten)
# x1_gen = np.random.uniform(10, 20, N_gen)
# x2_gen = np.random.uniform(10, 20, N_gen)

# y_gen = x1_gen * x2_gen   # oder * , -

# generalization_data = pd.DataFrame({
#     "x1": x1_gen,
#     "x2": x2_gen,
#     "y": y_gen
# })

# generalization_data.to_csv("multiplication_gen_dataset.csv", index=False)

# 2. SVM

In [ ]:
# =========================
# Imports
# =========================
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# Evaluation SETUP

RANDOM_STATE = 42
CV_SPLITS = 5

cv = KFold(
    n_splits=CV_SPLITS,
    shuffle=True,
    random_state=RANDOM_STATE
)


# Results DataFrame

results = pd.DataFrame(columns=[
    "model",
    "operator",
    "dataset_type",   # cv | test | generalization
    "mse",
    "mae",
    "rmse",
    "relative_error",
    "mape",
    "mse_std"         # only used for CV
])


# Logging function


def log_results(results_df, model_name, operator, dataset_type, y_true, y_pred, mse_std=np.nan):
    mse = mean_squared_error(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    relative_error = np.mean(np.abs(y_true - y_pred) / (np.abs(y_true) + 1e-8))
    mape = np.mean(np.abs((y_true - y_pred) / (y_true + 1e-8))) * 100

    new_row = {
        "model": model_name,
        "operator": operator,
        "dataset_type": dataset_type,
        "mse": mse,
        "mae": mae,
        "rmse": rmse,
        "relative_error": relative_error,
        "mape": mape,
        "mse_std": mse_std
    }

    return pd.concat(
        [results_df, pd.DataFrame([new_row])],
        ignore_index=True
    )

## 2.1 Addition

In [ ]:
# Load the dataset
data = pd.read_csv("addition_dataset.csv")

X = data[["x1", "x2"]].values
y = data["y"].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Model
svr_lin = SVR(kernel="linear", C=10, epsilon=0.01)


# Cross-Validation

cv_mse = -cross_val_score(
    svr_lin,
    X_train,
    y_train,
    scoring="neg_mean_squared_error",
    cv=cv
)

results.loc[len(results)] = {
    "model": "SVR",
    "operator": "addition",
    "dataset_type": "cv",
    "mse": cv_mse.mean(),
    "mae": np.nan,
    "rmse": np.sqrt(cv_mse.mean()),
    "relative_error": np.nan,
    "mape": np.nan,
    "mse_std": cv_mse.std()
}


# Final training

svr_lin.fit(X_train, y_train)

# Test prediction
y_pred = svr_lin.predict(X_test)

results = log_results(
    results,
    "SVR",
    "addition",
    "test",
    y_test,
    y_pred
)

In [ ]:
# Generalization Test (Extrapolation)
gen_data = pd.read_csv("addition_gen_dataset.csv")

X_gen = gen_data[["x1", "x2"]].values
y_gen = gen_data["y"].values


X_gen = scaler.transform(X_gen)

# Prediction with final trained model
y_pred_gen = svr_lin.predict(X_gen)

results = log_results(
    results,
    "SVR",
    "addition",
    "generalization",
    y_gen,
    y_pred_gen
)

In [6]:
results

,model,operator,dataset_type,mse,mae,rmse,relative_error,mape,mse_std
0,SVR,addition,cv,0.000024,NaN,0.004870,NaN,NaN,0.000008
1,SVR,addition,test,0.000017,0.003425,0.004162,0.001302,0.130188,NaN
2,SVR,addition,generalization,0.000232,0.015077,0.015221,0.000503,0.050290,NaN

## 2.2 Multiplikation - rbf-Kernel

In [ ]:
# Load the dataset
data = pd.read_csv("multiplication_dataset.csv")


data = data.sample(n=20000, random_state=42)

X = data[["x1", "x2"]].values
y = data["y"].values

# Train-Test-Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scaling (fit NUR auf Trainingsdaten)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#Model
svr_rbf = SVR(
    kernel="rbf",
    C=10,
    gamma="scale",
    epsilon=0.01
)

# Cross-Validation
cv_mse = -cross_val_score(
    svr_rbf,
    X_train,
    y_train,
    scoring="neg_mean_squared_error",
    cv=cv
)

results.loc[len(results)] = {
    "model": "SVR",
    "operator": "multiplication",
    "dataset_type": "cv",
    "mse": cv_mse.mean(),
    "mae": np.nan,
    "rmse": np.sqrt(cv_mse.mean()),
    "relative_error": np.nan,
    "mape": np.nan,
    "mse_std": cv_mse.std()
}

#Final training
svr_rbf.fit(X_train, y_train)

# Test prediction (Interpolation)
y_pred = svr_rbf.predict(X_test)

results = log_results(
    results,
    "SVR",
    "multiplication",
    "test",
    y_test,
    y_pred
)


print("C:", svr_rbf.C)
print("Epsilon:", svr_rbf.epsilon)
print("Kernel:", svr_rbf.kernel)
print("Gamma:", svr_rbf.gamma if hasattr(svr_rbf, "gamma") else None)

C: 10
Epsilon: 0.01
Kernel: rbf
Gamma: scale

In [8]:
# Generalization Test
gen_data = pd.read_csv("multiplication_gen_dataset.csv")

X_gen = gen_data[["x1", "x2"]].values
y_gen = gen_data["y"].values

X_gen = scaler.transform(X_gen)

y_pred_gen = svr_rbf.predict(X_gen)

results = log_results(results, "SVR", "multiplication", "generalization", y_gen, y_pred_gen)

In [9]:
results

,model,operator,dataset_type,mse,mae,rmse,relative_error,mape,mse_std
0,SVR,addition,cv,0.000024,NaN,0.004870,NaN,NaN,0.000008
1,SVR,addition,test,0.000017,0.003425,0.004162,0.001302,0.130188,NaN
2,SVR,addition,generalization,0.000232,0.015077,0.015221,0.000503,0.050290,NaN
3,SVR,multiplication,cv,0.042259,NaN,0.205570,NaN,NaN,0.006143
4,SVR,multiplication,test,0.030965,0.046582,0.175968,0.002191,0.219087,NaN
5,SVR,multiplication,generalization,29867.831134,148.789214,172.823121,0.601676,60.167591,NaN

# 3. Entscheidungsbäume & Random Forests

## 3.1 Addition Entscheidungsbäume

In [ ]:
# CSV laden
data = pd.read_csv("addition_dataset.csv")

# Features und Zielvariable
X = data[["x1", "x2"]].values
y = data["y"].values

# Train-Test-Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model
tree_addition = DecisionTreeRegressor(
    max_depth=10,
    random_state=42
)

# Cross-Validation
cv_mse = -cross_val_score(
    tree_addition,
    X_train,
    y_train,
    scoring="neg_mean_squared_error",
    cv=cv
)

results.loc[len(results)] = {
    "model": "tree",
    "operator": "addition",
    "dataset_type": "cv",
    "mse": cv_mse.mean(),
    "mae": np.nan,
    "rmse": np.sqrt(cv_mse.mean()),
    "relative_error": np.nan,
    "mape": np.nan,
    "mse_std": cv_mse.std()
}

# Final training
tree_addition.fit(X_train, y_train)

# Interpolation Test
y_pred = tree_addition.predict(X_test)

results = log_results(
    results,
    "tree",
    "addition",
    "test",
    y_test,
    y_pred
)


r2 = r2_score(y_test, y_pred)
print(f"R² (Test): {r2:.4f}")

R² (Test): 0.9989

In [11]:
# Generalization Test
gen_data = pd.read_csv("addition_gen_dataset.csv")

X_gen = gen_data[["x1", "x2"]].values
y_gen = gen_data["y"].values


y_pred_gen = tree_addition.predict(X_gen)

results = log_results(results, "tree", "addition", "generalization", y_gen, y_pred_gen)

In [12]:
results

,model,operator,dataset_type,mse,mae,rmse,relative_error,mape,mse_std
0,SVR,addition,cv,0.000024,NaN,0.004870,NaN,NaN,0.000008
1,SVR,addition,test,0.000017,0.003425,0.004162,0.001302,0.130188,NaN
2,SVR,addition,generalization,0.000232,0.015077,0.015221,0.000503,0.050290,NaN
3,SVR,multiplication,cv,0.042259,NaN,0.205570,NaN,NaN,0.006143
4,SVR,multiplication,test,0.030965,0.046582,0.175968,0.002191,0.219087,NaN
5,SVR,multiplication,generalization,29867.831134,148.789214,172.823121,0.601676,60.167591,NaN
6,tree,addition,cv,0.075366,NaN,0.274529,NaN,NaN,0.000677
7,tree,addition,test,0.073034,0.220094,0.270248,0.327435,32.744032,NaN
8,tree,addition,generalization,127.711425,10.536892,11.300948,0.338864,33.886360,NaN

## 3.2 Entscheidungsbaum - Multiplikation

In [ ]:

# CSV laden
data = pd.read_csv("multiplication_dataset.csv")

# Features und Zielvariable
X = data[["x1", "x2"]]
y = data["y"]

# Train-Test-Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Entscheidungsbaum (Regression)
tree_multi = DecisionTreeRegressor(
    max_depth=10,          
    random_state=42
)
cv_mse = -cross_val_score(
    tree_multi,
    X_train,
    y_train,
    scoring="neg_mean_squared_error",
    cv=cv
)

results.loc[len(results)] = {
    "model": "tree",
    "operator": "multiplication",
    "dataset_type": "cv",
    "mse": cv_mse.mean(),
    "mae": np.nan,
    "rmse": np.sqrt(cv_mse.mean()),
    "relative_error": np.nan,
    "mape": np.nan,
    "mse_std": cv_mse.std()
}

# Training
tree_multi.fit(X_train, y_train)

# Vorhersage
y_pred = tree_multi.predict(X_test)

# Evaluation
r2 = r2_score(y_test, y_pred)


print(f"R²: {r2:.4f}")

results = log_results(results, "tree", "multiplication", "test", y_test, y_pred)

R²: 0.9939

In [14]:
# Generalization Test
gen_data = pd.read_csv("multiplication_gen_dataset.csv")

X_gen = gen_data[["x1", "x2"]].values
y_gen = gen_data["y"].values


y_pred_gen = tree_multi.predict(X_gen)

results = log_results(results, "tree", "multiplication", "generalization", y_gen, y_pred_gen)

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

In [15]:
results

,model,operator,dataset_type,mse,mae,rmse,relative_error,mape,mse_std
0,SVR,addition,cv,0.000024,NaN,0.004870,NaN,NaN,0.000008
1,SVR,addition,test,0.000017,0.003425,0.004162,0.001302,0.130188,NaN
2,SVR,addition,generalization,0.000232,0.015077,0.015221,0.000503,0.050290,NaN
3,SVR,multiplication,cv,0.042259,NaN,0.205570,NaN,NaN,0.006143
4,SVR,multiplication,test,0.030965,0.046582,0.175968,0.002191,0.219087,NaN
5,SVR,multiplication,generalization,29867.831134,148.789214,172.823121,0.601676,60.167591,NaN
6,tree,addition,cv,0.075366,NaN,0.274529,NaN,NaN,0.000677
7,tree,addition,test,0.073034,0.220094,0.270248,0.327435,32.744032,NaN
8,tree,addition,generalization,127.711425,10.536892,11.300948,0.338864,33.886360,NaN
9,tree,multiplication,cv,13.764949,NaN,3.710114,NaN,NaN,19.908488
10,tree,multiplication,test,6.807573,1.914443,2.609133,0.269934,26.993391,NaN
11,tree,multiplication,generalization,19704.974806,126.032062,140.374409,0.525202,52.520177,NaN

## 3.3 Random Forest - Additon

In [ ]:
# CSV laden
data = pd.read_csv("addition_dataset.csv")

# Features und Zielvariable
X = data[["x1", "x2"]].values
y = data["y"].values

# Train-Test-Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model
forest_add = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    bootstrap=True,
    random_state=42,
    n_jobs=-1
)

# Cross-Validation
cv_mse = -cross_val_score(
    forest_add,
    X_train,
    y_train,
    scoring="neg_mean_squared_error",
    cv=cv
)

results.loc[len(results)] = {
    "model": "forest",
    "operator": "addition",
    "dataset_type": "cv",
    "mse": cv_mse.mean(),
    "mae": np.nan,
    "rmse": np.sqrt(cv_mse.mean()),
    "relative_error": np.nan,
    "mape": np.nan,
    "mse_std": cv_mse.std()
}

# Final training
forest_add.fit(X_train, y_train)

# Interpolation
y_pred = forest_add.predict(X_test)

results = log_results(
    results,
    "forest",
    "addition",
    "test",
    y_test,
    y_pred
)


r2 = r2_score(y_test, y_pred)
print(f"R² (Test): {r2:.4f}")

R² (Test): 0.9999

In [17]:
# Generalization Test
gen_data = pd.read_csv("addition_gen_dataset.csv")

X_gen = gen_data[["x1", "x2"]].values
y_gen = gen_data["y"].values


y_pred_gen = forest_add.predict(X_gen)

results = log_results(results, "forest", "addition", "generalization", y_gen, y_pred_gen)

In [18]:
results

,model,operator,dataset_type,mse,mae,rmse,relative_error,mape,mse_std
0,SVR,addition,cv,0.000024,NaN,0.004870,NaN,NaN,0.000008
1,SVR,addition,test,0.000017,0.003425,0.004162,0.001302,0.130188,NaN
2,SVR,addition,generalization,0.000232,0.015077,0.015221,0.000503,0.050290,NaN
3,SVR,multiplication,cv,0.042259,NaN,0.205570,NaN,NaN,0.006143
4,SVR,multiplication,test,0.030965,0.046582,0.175968,0.002191,0.219087,NaN
5,SVR,multiplication,generalization,29867.831134,148.789214,172.823121,0.601676,60.167591,NaN
6,tree,addition,cv,0.075366,NaN,0.274529,NaN,NaN,0.000677
7,tree,addition,test,0.073034,0.220094,0.270248,0.327435,32.744032,NaN
8,tree,addition,generalization,127.711425,10.536892,11.300948,0.338864,33.886360,NaN
9,tree,multiplication,cv,13.764949,NaN,3.710114,NaN,NaN,19.908488
10,tree,multiplication,test,6.807573,1.914443,2.609133,0.269934,26.993391,NaN
11,tree,multiplication,generalization,19704.974806,126.032062,140.374409,0.525202,52.520177,NaN
12,forest,addition,cv,0.008617,NaN,0.092829,NaN,NaN,0.000304
13,forest,addition,test,0.009008,0.071672,0.094913,0.098546,9.854731,NaN
14,forest,addition,generalization,127.326648,10.518618,11.283911,0.338242,33.824220,NaN

## 3.4 Random Forest - Multiplikation

In [ ]:
# CSV laden
data = pd.read_csv("multiplication_dataset.csv")

# Features und Zielvariable
X = data[["x1", "x2"]]
y = data["y"]

# Train-Test-Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Random Forest mit Bagging
forest_mul = RandomForestRegressor(
    n_estimators=200,      
    max_depth=10,          
    bootstrap=True,        
    random_state=42,
    n_jobs=-1
)

# Cross-Validation
cv_mse = -cross_val_score(
    forest_mul,
    X_train,
    y_train,
    scoring="neg_mean_squared_error",
    cv=cv
)

results.loc[len(results)] = {
    "model": "forest",
    "operator": "multiplication",
    "dataset_type": "cv",
    "mse": cv_mse.mean(),
    "mae": np.nan,
    "rmse": np.sqrt(cv_mse.mean()),
    "relative_error": np.nan,
    "mape": np.nan,
    "mse_std": cv_mse.std()
}

# Training
forest_mul.fit(X_train, y_train)

# Vorhersage
y_pred = forest_mul.predict(X_test)

# Evaluation
r2 = r2_score(y_test, y_pred)
print(f"R²: {r2:.4f}")

results = log_results(results, "forest", "multiplication", "test", y_test, y_pred)

R²: 0.9962

In [20]:
# Generalization Test
gen_data = pd.read_csv("multiplication_gen_dataset.csv")

X_gen = gen_data[["x1", "x2"]].values
y_gen = gen_data["y"].values


y_pred_gen = forest_mul.predict(X_gen)

results = log_results(results, "forest", "multiplication", "generalization", y_gen, y_pred_gen)

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [21]:
results

,model,operator,dataset_type,mse,mae,rmse,relative_error,mape,mse_std
0,SVR,addition,cv,0.000024,NaN,0.004870,NaN,NaN,0.000008
1,SVR,addition,test,0.000017,0.003425,0.004162,0.001302,0.130188,NaN
2,SVR,addition,generalization,0.000232,0.015077,0.015221,0.000503,0.050290,NaN
3,SVR,multiplication,cv,0.042259,NaN,0.205570,NaN,NaN,0.006143
4,SVR,multiplication,test,0.030965,0.046582,0.175968,0.002191,0.219087,NaN
5,SVR,multiplication,generalization,29867.831134,148.789214,172.823121,0.601676,60.167591,NaN
6,tree,addition,cv,0.075366,NaN,0.274529,NaN,NaN,0.000677
7,tree,addition,test,0.073034,0.220094,0.270248,0.327435,32.744032,NaN
8,tree,addition,generalization,127.711425,10.536892,11.300948,0.338864,33.886360,NaN
9,tree,multiplication,cv,13.764949,NaN,3.710114,NaN,NaN,19.908488
10,tree,multiplication,test,6.807573,1.914443,2.609133,0.269934,26.993391,NaN
11,tree,multiplication,generalization,19704.974806,126.032062,140.374409,0.525202,52.520177,NaN
12,forest,addition,cv,0.008617,NaN,0.092829,NaN,NaN,0.000304
13,forest,addition,test,0.009008,0.071672,0.094913,0.098546,9.854731,NaN
14,forest,addition,generalization,127.326648,10.518618,11.283911,0.338242,33.824220,NaN
15,forest,multiplication,cv,2.388711,NaN,1.545546,NaN,NaN,0.957205
16,forest,multiplication,test,4.211338,1.356067,2.052154,0.240036,24.003575,NaN
17,forest,multiplication,generalization,21130.523655,131.566065,145.363419,0.551828,55.182797,NaN

# 4. Neuronale Netze

In [22]:
def build_nn():
    model = Sequential([
        Dense(32, activation="relu", input_shape=(2,)),
        Dense(32, activation="relu"),
        Dense(1)
    ])
    model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss="mse"
    )
    return model

## 4.1 NN - Addition

In [ ]:
# Datensatz laden
data = pd.read_csv("addition_dataset.csv")

X = data[["x1", "x2"]].values
y = data["y"].values

# Train-Test-Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Cross-Validation
cv_mse = []

for train_idx, val_idx in cv.split(X_train):
    X_tr, X_val = X_train[train_idx], X_train[val_idx]
    y_tr, y_val = y_train[train_idx], y_train[val_idx]

    scaler = StandardScaler()
    X_tr = scaler.fit_transform(X_tr)
    X_val = scaler.transform(X_val)

    nn = build_nn()
    nn.fit(
        X_tr,
        y_tr,
        epochs=50,
        batch_size=128,
        verbose=0
    )

    y_val_pred = nn.predict(X_val).flatten()
    mse = mean_squared_error(y_val, y_val_pred)
    cv_mse.append(mse)

cv_mse = np.array(cv_mse)

results.loc[len(results)] = {
    "model": "neural_network",
    "operator": "addition",
    "dataset_type": "cv",
    "mse": cv_mse.mean(),
    "mae": np.nan,
    "rmse": np.sqrt(cv_mse.mean()),
    "relative_error": np.nan,
    "mape": np.nan,
    "mse_std": cv_mse.std()
}

# Finales Training
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = build_nn()
model.fit(
    X_train_scaled,
    y_train,
    epochs=50,
    batch_size=128,
    verbose=1
)

#Interpolation
y_pred = model.predict(X_test_scaled).flatten()

results = log_results(
    results,
    "neural_network",
    "addition",
    "test",
    y_test,
    y_pred
)

r2 = r2_score(y_test, y_pred)
print(f"R² (Test): {r2:.4f}")

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 212us/step

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 206us/step

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 208us/step

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 199us/step

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 208us/step
Epoch 1/50

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 405us/step - loss: 8.4868
Epoch 2/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 341us/step - loss: 0.0554
Epoch 3/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 362us/step - loss: 0.0050
Epoch 4/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - loss: 0.0013
Epoch 5/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 324us/step - loss: 7.3223e-04
Epoch 6/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 341us/step - loss: 5.3165e-04
Epoch 7/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 337us/step - loss: 3.9743e-04
Epoch 8/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - loss: 2.9830e-04
Epoch 9/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - loss: 2.0433e-04
Epoch 10/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - loss: 1.3616e-04
Epoch 11/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 327us/step - loss: 1.0317e-04
Epoch 12/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - loss: 8.0973e-05
Epoch 13/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - loss: 6.1421e-05
Epoch 14/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - loss: 4.8863e-05
Epoch 15/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - loss: 4.3359e-05
Epoch 16/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 398us/step - loss: 4.1388e-05
Epoch 17/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - loss: 7.1473e-05
Epoch 18/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - loss: 2.4605e-05
Epoch 19/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 337us/step - loss: 4.5128e-05
Epoch 20/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 319us/step - loss: 5.3263e-05
Epoch 21/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - loss: 4.1011e-05
Epoch 22/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - loss: 2.6150e-05
Epoch 23/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 319us/step - loss: 3.7860e-05
Epoch 24/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 317us/step - loss: 3.8791e-05
Epoch 25/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - loss: 4.2187e-05
Epoch 26/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - loss: 1.5719e-05
Epoch 27/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 316us/step - loss: 3.4115e-05
Epoch 28/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - loss: 4.1139e-05
Epoch 29/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - loss: 2.4114e-05
Epoch 30/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - loss: 3.3990e-05
Epoch 31/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 317us/step - loss: 3.1752e-05
Epoch 32/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 325us/step - loss: 3.2147e-05
Epoch 33/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 327us/step - loss: 3.5924e-05
Epoch 34/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 316us/step - loss: 3.5776e-05
Epoch 35/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - loss: 4.3595e-05
Epoch 36/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 319us/step - loss: 6.0019e-05
Epoch 37/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 315us/step - loss: 1.9745e-06
Epoch 38/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - loss: 6.0981e-05
Epoch 39/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 317us/step - loss: 2.6110e-05
Epoch 40/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - loss: 2.4664e-05
Epoch 41/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 327us/step - loss: 3.9017e-05
Epoch 42/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - loss: 2.0088e-05
Epoch 43/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - loss: 4.7936e-05
Epoch 44/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 317us/step - loss: 1.1602e-05
Epoch 45/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 319us/step - loss: 7.5093e-05
Epoch 46/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - loss: 3.9432e-06
Epoch 47/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 317us/step - loss: 3.3427e-05
Epoch 48/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - loss: 5.6939e-05
Epoch 49/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - loss: 1.8455e-05
Epoch 50/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 319us/step - loss: 4.4260e-05
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 201us/step
R² (Test): 1.0000

In [24]:
# Generalization Test
gen_data = pd.read_csv("addition_gen_dataset.csv")

X_gen = gen_data[["x1", "x2"]].values
y_gen = gen_data["y"].values

X_gen = scaler.transform(X_gen)

y_pred_gen = model.predict(X_gen).flatten()

results = log_results(results, "neural_network", "addition", "generalization", y_gen, y_pred_gen)

3125/3125 ━━━━━━━━━━━━━━━━━━━━ 1s 191us/step

In [25]:
results

,model,operator,dataset_type,mse,mae,rmse,relative_error,mape,mse_std
0,SVR,addition,cv,0.000024,NaN,0.004870,NaN,NaN,0.000008
1,SVR,addition,test,0.000017,0.003425,0.004162,0.001302,0.130188,NaN
2,SVR,addition,generalization,0.000232,0.015077,0.015221,0.000503,0.050290,NaN
3,SVR,multiplication,cv,0.042259,NaN,0.205570,NaN,NaN,0.006143
4,SVR,multiplication,test,0.030965,0.046582,0.175968,0.002191,0.219087,NaN
5,SVR,multiplication,generalization,29867.831134,148.789214,172.823121,0.601676,60.167591,NaN
6,tree,addition,cv,0.075366,NaN,0.274529,NaN,NaN,0.000677
7,tree,addition,test,0.073034,0.220094,0.270248,0.327435,32.744032,NaN
8,tree,addition,generalization,127.711425,10.536892,11.300948,0.338864,33.886360,NaN
9,tree,multiplication,cv,13.764949,NaN,3.710114,NaN,NaN,19.908488
10,tree,multiplication,test,6.807573,1.914443,2.609133,0.269934,26.993391,NaN
11,tree,multiplication,generalization,19704.974806,126.032062,140.374409,0.525202,52.520177,NaN
12,forest,addition,cv,0.008617,NaN,0.092829,NaN,NaN,0.000304
13,forest,addition,test,0.009008,0.071672,0.094913,0.098546,9.854731,NaN
14,forest,addition,generalization,127.326648,10.518618,11.283911,0.338242,33.824220,NaN
15,forest,multiplication,cv,2.388711,NaN,1.545546,NaN,NaN,0.957205
16,forest,multiplication,test,4.211338,1.356067,2.052154,0.240036,24.003575,NaN
17,forest,multiplication,generalization,21130.523655,131.566065,145.363419,0.551828,55.182797,NaN
18,neural_network,addition,cv,0.000041,NaN,0.006396,NaN,NaN,0.000059
19,neural_network,addition,test,0.000001,0.000784,0.001060,0.000708,0.070800,NaN
20,neural_network,addition,generalization,0.370072,0.564304,0.608336,0.018112,1.811247,NaN

## 4.2 NN - Multiplikation

In [ ]:
# Datensatz laden
data = pd.read_csv("multiplication_dataset.csv")

X = data[["x1", "x2"]].values
y = data["y"].values

# Train-Test-Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Cross-Validation
cv_mse = []

for train_idx, val_idx in cv.split(X_train):
    X_tr, X_val = X_train[train_idx], X_train[val_idx]
    y_tr, y_val = y_train[train_idx], y_train[val_idx]

    scaler = StandardScaler()
    X_tr = scaler.fit_transform(X_tr)
    X_val = scaler.transform(X_val)

    nn = build_nn()
    nn.fit(
        X_tr,
        y_tr,
        epochs=50,
        batch_size=128,
        verbose=0
    )

    y_val_pred = nn.predict(X_val).flatten()
    mse = mean_squared_error(y_val, y_val_pred)
    cv_mse.append(mse)

cv_mse = np.array(cv_mse)

results.loc[len(results)] = {
    "model": "neural_network",
    "operator": "multiplication",
    "dataset_type": "cv",
    "mse": cv_mse.mean(),
    "mae": np.nan,
    "rmse": np.sqrt(cv_mse.mean()),
    "relative_error": np.nan,
    "mape": np.nan,
    "mse_std": cv_mse.std()
}

# Finales Training
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model_mul = build_nn()
model_mul.fit(
    X_train_scaled,
    y_train,
    epochs=50,
    batch_size=128,
    verbose=1
)

# Interpolation
y_pred = model_mul.predict(X_test_scaled).flatten()

results = log_results(
    results,
    "neural_network",
    "multiplication",
    "test",
    y_test,
    y_pred
)

r2 = r2_score(y_test, y_pred)
print(f"R² (Test): {r2:.4f}")

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 210us/step

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 203us/step

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 202us/step

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 208us/step

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 211us/step
Epoch 1/50

/Users/eliaspfeiffer/Developer/ML_math/.venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 331us/step - loss: 391.6309
Epoch 2/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - loss: 14.9793
Epoch 3/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 325us/step - loss: 4.5315
Epoch 4/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - loss: 1.6513
Epoch 5/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - loss: 0.8322
Epoch 6/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - loss: 0.4633
Epoch 7/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - loss: 0.2983
Epoch 8/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 339us/step - loss: 0.2178
Epoch 9/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - loss: 0.1738
Epoch 10/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 341us/step - loss: 0.1486
Epoch 11/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 340us/step - loss: 0.1349
Epoch 12/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 326us/step - loss: 0.1209
Epoch 13/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - loss: 0.1146
Epoch 14/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 342us/step - loss: 0.1095
Epoch 15/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 329us/step - loss: 0.1028
Epoch 16/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 328us/step - loss: 0.1004
Epoch 17/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 331us/step - loss: 0.0984
Epoch 18/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - loss: 0.1006
Epoch 19/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 324us/step - loss: 0.0949
Epoch 20/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - loss: 0.0906
Epoch 21/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - loss: 0.0926
Epoch 22/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 317us/step - loss: 0.0899
Epoch 23/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 323us/step - loss: 0.0889
Epoch 24/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 328us/step - loss: 0.0868
Epoch 25/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - loss: 0.0850
Epoch 26/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - loss: 0.0838
Epoch 27/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 317us/step - loss: 0.0829
Epoch 28/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - loss: 0.0819
Epoch 29/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 319us/step - loss: 0.0797
Epoch 30/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - loss: 0.0811
Epoch 31/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 323us/step - loss: 0.0776
Epoch 32/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - loss: 0.0755
Epoch 33/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - loss: 0.0780
Epoch 34/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - loss: 0.0761
Epoch 35/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - loss: 0.0746
Epoch 36/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 315us/step - loss: 0.0742
Epoch 37/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - loss: 0.0747
Epoch 38/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 326us/step - loss: 0.0731
Epoch 39/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 331us/step - loss: 0.0714
Epoch 40/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - loss: 0.0723
Epoch 41/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - loss: 0.0721
Epoch 42/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - loss: 0.0709
Epoch 43/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - loss: 0.0711
Epoch 44/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - loss: 0.0721
Epoch 45/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 330us/step - loss: 0.0688
Epoch 46/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 319us/step - loss: 0.0714
Epoch 47/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 319us/step - loss: 0.0694
Epoch 48/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - loss: 0.0694
Epoch 49/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - loss: 0.0700
Epoch 50/50
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - loss: 0.0702
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 204us/step
R² (Test): 0.9999

In [27]:
gen_data = pd.read_csv("multiplication_gen_dataset.csv")

X_gen = gen_data[["x1", "x2"]].values
y_gen = gen_data["y"].values

X_gen = scaler.transform(X_gen)

y_pred_gen = model_mul.predict(X_gen).flatten()

results = log_results(results, "neural_network", "multiplication", "generalization", y_gen, y_pred_gen)

3125/3125 ━━━━━━━━━━━━━━━━━━━━ 1s 194us/step

In [28]:
results

,model,operator,dataset_type,mse,mae,rmse,relative_error,mape,mse_std
0,SVR,addition,cv,0.000024,NaN,0.004870,NaN,NaN,0.000008
1,SVR,addition,test,0.000017,0.003425,0.004162,0.001302,0.130188,NaN
2,SVR,addition,generalization,0.000232,0.015077,0.015221,0.000503,0.050290,NaN
3,SVR,multiplication,cv,0.042259,NaN,0.205570,NaN,NaN,0.006143
4,SVR,multiplication,test,0.030965,0.046582,0.175968,0.002191,0.219087,NaN
5,SVR,multiplication,generalization,29867.831134,148.789214,172.823121,0.601676,60.167591,NaN
6,tree,addition,cv,0.075366,NaN,0.274529,NaN,NaN,0.000677
7,tree,addition,test,0.073034,0.220094,0.270248,0.327435,32.744032,NaN
8,tree,addition,generalization,127.711425,10.536892,11.300948,0.338864,33.886360,NaN
9,tree,multiplication,cv,13.764949,NaN,3.710114,NaN,NaN,19.908488
10,tree,multiplication,test,6.807573,1.914443,2.609133,0.269934,26.993391,NaN
11,tree,multiplication,generalization,19704.974806,126.032062,140.374409,0.525202,52.520177,NaN
12,forest,addition,cv,0.008617,NaN,0.092829,NaN,NaN,0.000304
13,forest,addition,test,0.009008,0.071672,0.094913,0.098546,9.854731,NaN
14,forest,addition,generalization,127.326648,10.518618,11.283911,0.338242,33.824220,NaN
15,forest,multiplication,cv,2.388711,NaN,1.545546,NaN,NaN,0.957205
16,forest,multiplication,test,4.211338,1.356067,2.052154,0.240036,24.003575,NaN
17,forest,multiplication,generalization,21130.523655,131.566065,145.363419,0.551828,55.182797,NaN
18,neural_network,addition,cv,0.000041,NaN,0.006396,NaN,NaN,0.000059
19,neural_network,addition,test,0.000001,0.000784,0.001060,0.000708,0.070800,NaN
20,neural_network,addition,generalization,0.370072,0.564304,0.608336,0.018112,1.811247,NaN
21,neural_network,multiplication,cv,0.083568,NaN,0.289081,NaN,NaN,0.011129
22,neural_network,multiplication,test,0.076569,0.218184,0.276711,0.124040,12.403992,NaN
23,neural_network,multiplication,generalization,6234.181727,68.602290,78.956835,0.279489,27.948927,NaN